/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import java.util.Collection;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-11-2019
 * 
 * XDoclet definition:
 * @struts.form name="indexForm"
 */
public class IndexForm extends ActionForm {
	String txtcard,txtpin,ddvalid,btnsubmit ;
	public String getBtnsubmit() {
		return btnsubmit;
	}

	public void setBtnsubmit(String btnsubmit) {
		this.btnsubmit = btnsubmit;
	}

	Collection collectionid;
	public String getTxtcard() {
		return txtcard;
	}

	public void setTxtcard(String txtcard) {
		this.txtcard = txtcard;
	}

	public String getTxtpin() {
		return txtpin;
	}

	public void setTxtpin(String txtpin) {
		this.txtpin = txtpin;
	}

	public String getDdvalid() {
		return ddvalid;
	}

	public void setDdvalid(String ddvalid) {
		this.ddvalid = ddvalid;
	}

	public Collection getCollectionid() {
		return collectionid;
	}

	public void setCollectionid(Collection collectionid) {
		this.collectionid = collectionid;
	}

	
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}