/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.sql.Connection;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import p1.Myconnection;
import p2.atmdao;

import com.yourcompany.struts.form.AccountypeForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-24-2019
 * 
 * XDoclet definition:
 * @struts.action path="/accountype" name="accountypeForm" input="/form/accountype.jsp" scope="request" validate="true"
 */
public class AccountypeAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AccountypeForm accountypeForm = (AccountypeForm) form;// TODO Auto-generated method stub
		Connection con=Myconnection.mycon();
		atmdao obj=new atmdao();
		HttpSession session=request.getSession();
		String st=(String)session.getAttribute("cardno");
		
		ArrayList ar=obj.getaccd(con,st);
		String st1=(String)ar.get(0);
		if(st1.equals(accountypeForm.getAcctype())){
			return mapping.findForward("transtype");
			
			
		}
		else{
			request.setAttribute("ms2", "account type not matched");
			return mapping.getInputForward();
		}
		
		
	}
}