/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Collection;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import p1.Myconnection;
import p2.atmdao;

import com.yourcompany.struts.form.CashwithdrawForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-25-2019
 * 
 * XDoclet definition:
 * @struts.action path="/cashwithdraw" name="cashwithdrawForm" input="/form/cashwithdraw.jsp" scope="request" validate="true"
 */
public class CashwithdrawAction extends Action {
	/*
	 * Generated Methods
	 */PreparedStatement ps=null;
	 ResultSet rs=null;

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CashwithdrawForm cwf = (CashwithdrawForm) form;// TODO Auto-generated method stub
		Connection con=Myconnection.mycon();
		atmdao obj=new atmdao();
		HttpSession session1=request.getSession();
		String st5=(String)session1.getAttribute("cardno");
		try{
			ps=con.prepareStatement("select amount from atmcard where cardno='"+st5+"'");
			rs=ps.executeQuery();
			if(rs.next()){
				String st1=rs.getString(1);
				System.out.println(st1);
				int amount=Integer.parseInt(st1);
				System.out.println(amount);
				String st2=cwf.getTxtamount();
				int amount1=Integer.parseInt(st2);
				System.out.println(amount1);
				if(amount1<amount){
					int a=amount-amount1;
					String st3=String.valueOf(a);
					System.out.println(st3);
					int st4=obj.updateatmdtl(con, st3, st5);
					
					if(st4>0){
						String str=obj.tid(con);
						int str1=obj.insertdtl(con, str, st5, "withdrawal");
						
						
						
						if(str1>0){
						request.setAttribute("ms2", "Amount Withdrawn......");
						}
					}else{
						request.setAttribute("ms2", "not suffient funds to withdraw..");
					}
				}
				
				
			}
			
		}catch(SQLException e){
			
		}
		return mapping.getInputForward();
	}
}