/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import p1.Myconnection;
import p2.atmdao;
import p2.fillddd;

import com.yourcompany.struts.form.IndexForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-11-2019
 * 
 * XDoclet definition:
 * @struts.action path="/index" name="indexForm" input="/form/index.jsp" scope="request" validate="true"
 */
public class IndexAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		IndexForm indexForm = (IndexForm) form;// TODO Auto-generated method stub
		fillddd obj=new fillddd();
	Connection con=Myconnection.mycon();
	HttpSession session=request.getSession();
	ArrayList ar=obj.fillddvalid(con);
	indexForm.setCollectionid(ar);
	atmdao obj1=new atmdao();
	if(indexForm.getBtnsubmit()!=null)
		
	{
		try
		{
		ArrayList ar1=obj1.getuserdtl(con,indexForm.getTxtcard(),indexForm.getTxtpin(),indexForm.getDdvalid());
		String st1=(String)ar1.get(0);
		String st2=(String)ar1.get(1);
		String st3=(String)ar1.get(2);
		if((st1.equals(indexForm.getTxtcard()))&&(st2.equals(indexForm.getTxtpin()))&&(st3.equals(indexForm.getDdvalid())))
		{
			request.setAttribute("ms2","login successful...");
			session.setAttribute("cardno", st1);
			return mapping.findForward("acctype");
		}
		else{
			request.setAttribute("ms2", "login failed...");
		}
		}catch(Exception e){
			System.out.println(e.getMessage());
			
		}
		
	}
	
	return mapping.getInputForward();
	
	}
}