/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.sql.Connection;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import p1.Myconnection;

import p2.atmdao;

import com.yourcompany.struts.form.ViewstatementForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-25-2019
 * 
 * XDoclet definition:
 * @struts.action path="/viewstatement" name="viewstatementForm" input="/form/viewstatement.jsp" scope="request" validate="true"
 */
public class ViewstatementAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ViewstatementForm viewstatementForm = (ViewstatementForm) form;// TODO Auto-generated method stub
		Connection cn=Myconnection.mycon();
		atmdao obj1=new atmdao();
		HttpSession session1=request.getSession();
		String st5=(String)session1.getAttribute("cardno");
		ArrayList ar= obj1.gettrandtl(cn,st5);
		if(ar.isEmpty())
		{
			request.setAttribute("ms1", "Sorry!Information Not Available.........");
		}
		else
		{			
			request.setAttribute("list", ar);
			request.setAttribute("ms1", "Thank You!Visit Again!.........");
			
		}
		return mapping.getInputForward();
	}

	}
